apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lam
  namespace: lam
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: iconicompany.com
      hosts:
        - iconicompany.com
  rules:
  - host: iconicompany.com
    http:
      paths:
      - path: /lam
        pathType: Prefix
        backend:
          service:
            name: lam
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: lam
  namespace: lam
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app:  lam
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lam-pvc
  namespace: lam
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lam
  namespace: lam
spec:
  selector:
    matchLabels:
      app: lam
  replicas: 1
  template:
    metadata:
      labels:
        app: lam
    spec:
      containers:
      - name: lam
        image: ldapaccountmanager/lam:stable
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: lam-config

